;; Initialize package sources
(require 'package)
(global-set-key [C-mouse-4] 'text-scale-increase)
(global-set-key [C-mouse-5] 'text-scale-decrease)
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

;; Install use-package if not already installed
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

;; Custom-set variables (generated by Emacs Customize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(lsp-ui company racer git yaml-mode spacemacs-theme lsp-mode smartparens treemacs python-mode rustic)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; Additional appearance settings
(add-to-list 'default-frame-alist '(background-color . "#262626"))

;; Smartparens for structured editing
(require 'smartparens)
(smartparens-global-mode 1)

;; Enable windmove for easy window navigation
(windmove-default-keybindings)

;; Scroll settings
(setq redisplay-dont-pause t
      scroll-margin 1
      scroll-step 1
      scroll-conservatively 10000
      scroll-preserve-screen-position 1)

;; LSP configuration for Python using pylsp
(use-package lsp-mode
  :hook (python-mode . lsp)
  :commands lsp
  :config
  (setq lsp-clients-python-command "pylsp"))

;; LSP UI for additional UI integrations
(use-package lsp-ui
  :commands lsp-ui-mode)

;; Company mode for autocompletion
(use-package company
  :config
  (global-company-mode))

;; Flycheck for syntax checking
(use-package flycheck
  :init (global-flycheck-mode))
